[package]
name = "bevy-ui-navigation"
authors = ["Nicola Papale"]
description = "A bevy plugin to make implementing ui navigation in your game a piece of cake"
license = "MIT OR Apache-2.0"
readme = "Readme.md"
keywords = ["bevy", "ui", "navigation", "keyboard", "gamepad"]
categories = ["game-development", "accessibility", "gui"]
repository = "https://github.com/nicopap/ui-navigation"
homepage = "https://github.com/nicopap/ui-navigation"
exclude = ["assets", ".github"]
version = "0.17.0"
edition = "2021"

[features]
default = ["bevy-ui"]
bevy-ui = ["bevy/render"]

[dependencies]
bevy = { version = "0.7.0", default-features = false }
non-empty-vec = { version = "0.2.2", default-features = false }

[dev-dependencies]
bevy = { version = "0.7.0", default-features = false, features = ["render", "x11", "png", "bevy_gilrs" ] }
bevy-ui-build-macros = "0.2.1"

