[package]
name = "bevy-ui-navigation"
authors = ["Nicola Papale"]
description = "A bevy plugin to make implementing ui navigation in your game a piece of cake"
license = "MIT OR Apache-2.0"
readme = "Readme.md"
keywords = ["bevy", "ui", "navigation", "keyboard", "gamepad"]
categories = ["game-development", "accessibility", "gui"]
repository = "https://github.com/nicopap/ui-navigation"
homepage = "https://github.com/nicopap/ui-navigation"
exclude = ["assets"]
version = "0.7.1"
edition = "2021"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy.git", default-features = false, features = ["render"] }
non-empty-vec = { version = "0.2.2", default-features = false }

[dev-dependencies]
bevy = { git = "https://github.com/bevyengine/bevy.git", default-features = false, features = ["render", "bevy_wgpu", "x11", "png", "bevy_gilrs" ] }
bevy-ui-build-macros = "0.1"

