[package]
name = "bevy-ui-navigation"
authors = ["Nicola Papale"]
description = "A bevy plugin to make implementing ui navigation in your game a piece of cake"
license = "MIT OR Apache-2.0"
readme = "Readme.md"
keywords = ["bevy", "ui", "navigation", "keyboard", "gamepad"]
categories = ["game-development", "accessibility", "gui"]
repository = "https://github.com/nicopap/ui-navigation"
homepage = "https://github.com/nicopap/ui-navigation"
exclude = ["assets", ".github"]
version = "0.27.0"
edition = "2021"

[features]
default = ["bevy_ui", "bevy_reflect"]
bevy_reflect = []
bevy_ui = ["bevy/bevy_ui", "bevy/bevy_render"]

[dependencies]
bevy = { version = "0.11", default-features = false, features = ["bevy_asset"] }
cuicui_dsl = { version = "0.6.0", optional = true }
non-empty-vec = { version = "0.2.2", default-features = false }

[dev-dependencies]
fastrand = "1.7"
# bevy-inspector-egui = "0.19"
# bevy_framepace = "0.12.1"
cuicui_layout_bevy_ui = "0.6.0"
cuicui_layout = "0.6.0"
bevy = { version = "0.11", default-features = true }

[[example]]
name = "ultimate_menu_navigation"
required-features = ["cuicui_dsl"]
